# Generated by Django 4.2.2 on 2023-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
