# Generated by Django 4.2.2 on 2023-06-25 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_friendslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intended_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_friendship_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
