# Generated by Django 4.2.2 on 2023-06-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendshipnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendshipnotification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
