# Generated by Django 4.2.2 on 2023-06-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friendshipnotification_is_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshipnotification',
            options={'ordering': ('-created_at',)},
        ),
    ]
