# Generated by Django 4.2.2 on 2023-06-30 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import friends.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0005_alter_friendshipnotification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_one', models.ForeignKey(default=friends.models.Conversation.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='conversations_member_one', to=settings.AUTH_USER_MODEL)),
                ('member_two', models.ForeignKey(default=friends.models.Conversation.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='conversations_member_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
