# Generated by Django 4.2.2 on 2023-07-04 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import friends.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0006_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='friends.conversation')),
                ('sent_by', models.ForeignKey(default=friends.models.ConversationMessage.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='my_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
