# Generated by Django 4.2.2 on 2023-07-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='text',
            field=models.CharField(default='default text', max_length=400),
        ),
        migrations.AlterModelTable(
            name='conversationmessage',
            table='messages',
        ),
    ]
