# Generated by Django 4.2.2 on 2023-07-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0008_conversationmessage_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'verbose_name_plural': 'messages'},
        ),
    ]
