# Generated by Django 4.2.2 on 2023-06-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
    ]
