# Generated by Django 4.2.2 on 2023-06-17 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0003_photo_number_of_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0006_comment_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_like', models.BooleanField()),
                ('is_comment', models.BooleanField()),
                ('is_seen', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='photoshare.photo')),
            ],
        ),
    ]
